platform :ios, '13.0'

source 'https://cdn.cocoapods.org/'

workspace 'LikemindsChatSample.xcworkspace'

target 'LikemindsChatSample' do
  project 'LikemindsChatSample.xcodeproj'
  
  use_frameworks!

  # Pods for LikemindsChatSample
 pod 'LikeMindsChatData', path: '../../likeminds-chat-ios-data/LikeMindsChatData.podspec'
 pod 'LikeMindsChatUI', path: '../LikeMindsChatUI.podspec'
 pod 'LikeMindsChatCore', path: '../LikeMindsChatCore.podspec'
 
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.0'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
