platform :ios, '13.0'

workspace 'LikemindsChatSample.xcworkspace'

target 'LikemindsChatSample' do
  project 'LikemindsChatSample.xcodeproj'
  
  use_frameworks!

  # Pods for LikemindsChatSample
 pod 'LikeMindsChatData'
 pod 'LikeMindsChatUI'
 pod 'LikeMindsChatCore'
 
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.0'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
